### ISSUE TITLE
Wish there will be a windows version.

### ISSUE THREAD

**Issue by gepcel** [has2k1/scikit-misc-wheels#2]
I'm trying plotnine, fantastic. Sometimes plotnine needs scikit-misc, but there's no windows version. And `pip install scikit-misc` also fails. Hope there will be a windows version.

**Comment by has2k1** [comment]
`scikit-misc`, currently only with a `loess` subpackage has `cython`,  `c` and `fortran` code. This makes it difficult to compile and create binary wheels that you can install with `pip`. For linux and OSX, the [multibuild](https://github.com/matthew-brett/multibuild) project makes it possible to create wheels. For Windows, there is no such project that I am aware of.

Also, given the scope of the package so far, there is no hope that it would be picked up by anaconda. Sorry for the bummer.

**Comment by has2k1** [comment]
@gepcel, Why close it?

**Comment by gepcel** [comment]
I thought there was no plan to support windows, at least not recently. So this can be closed? 

I wish there will be some way to work under windows system, either via conda or the well known web http://www.lfd.uci.edu/~gohlke/pythonlibs/

Actually, I tried something today, but couldn't make it work, not good at these kinds of stuff.. Since this wish seems impossible, I just closed it. 

I'm fine if you reopen it.

**Comment by has2k1** [comment]
I was aware of Gohlke's windows binaries, though I am not sure how he picks the packages. If recall correctly, there seemed to be a correlation with packages on Conda.

**Comment by gepcel** [comment]
Seems that packages like pandas or matplotlib used  [appveyor](https://www.appveyor.com/) services to auto-build their wheels of windows os.

**Comment by has2k1** [comment]
I think some one manually builds windows wheels for Matplotlib. There was an attempt to do it with appveyor but I don't think it was successful.

**Comment by has2k1** [comment]
@gepcel, can you try installing a wheel from http://www.lfd.uci.edu/~gohlke/pythonlibs/#scikit-misc for you arch and let me know how it turns out.

**Comment by gepcel** [comment]
Sorry for the late reponse. It worked `(for scikit_misc‑0.1.1‑cp36‑cp36m‑win_amd64.whl)`. Thank you very much for your work.

**Comment by has2k1** [comment]
Great. Thanks for helping out. I will upload those wheels to PyPi.
